version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - mvn clean
  build:
    commands:
      - mvn package -DskipTests=true

artifacts:
  files:
    - target/*.jar