version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Fetching BUILD_API flag..."
      - BUILD_API=$(aws ssm get-parameter --name "/pipeline/BUILD_API" --with-decryption --query "Parameter.Value" --output text)
      - echo "BUILD_API is $BUILD_API"
      - echo "$BUILD_API" > build_flag.txt
      - rm -rf target/*.jar || true  # Clean up previous builds

  pre_build:
    commands:
      - echo "Pre-build step: cleaning"
      - mvn clean

  build:
    commands:
      - if [ "$(cat build_flag.txt)" = "false" ]; then echo "Skipping actual build phase"; exit 0; fi
      - echo "Running mvn package"
      - mvn package -DskipTests=true

  post_build:
    commands:
      - if [ "$(cat build_flag.txt)" = "false" ]; then echo "Resetting flag only (no build done)"; else echo "Resetting BUILD_API flag to false"; fi
      - aws ssm put-parameter --name "/pipeline/BUILD_API" --value "false" --type "String" --overwrite

artifacts:
  files:
    - target/*.jar